version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Installing dependencies
          command: |
            npm install      
      - run:
          name: Linting
          command: |
            npm run lint
      - run:
          name: App Build
          command: |
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./*


  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - attach_workspace:
          at: ./
      - run:
          name: Jasmine Tests
          command: |
            npm run test
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: ./
      - aws-eb/setup
      - run:
          name: App Deploy
          command: |
            pwd
            ls
            eb init -p "Node.js 16 running on 64bit Amazon Linux 2" --region us-east-1 udacity-storefront-backend
            eb deploy udacity-storefront-backend-prod
            eb status
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
