version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - aws-eb/setup
      - checkout
      - run:
          name: Installing dependencies
          command: |
            npm install      
      - run:
          name: Linting
          command: |
            npm run lint
      - run:
          name: App Build
          command: |
            npm run build
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Jasmine Tests
          command: |
            npm run test
  deploy:
      working_directory: ~/udacity-storefront-backend/dist
      - run:
          name: App Deploy
          command: |
            cd dist
            eb init -p "Node.js 16 running on 64bit Amazon Linux 2" --region us-east-1 udacity-storefront-backend
            eb deploy udacity-storefront-backend-prod
            eb status
